name: lobe-chat-development
services:
  network-service:
    image: alpine
    container_name: lobe-network
    restart: always
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
      - '9001:9001' # MinIO Console
      - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
    command: tail -f /dev/null
    networks:
      - lobe-network

  postgresql:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: postgresql
  minio:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: minio
  casdoor:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: casdoor
  searxng:
    extends:
      file: docker-compose/local/docker-compose.yml
      service: searxng

volumes:
  data:
    driver: local
  s3_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
