description: LobeHub Prompts Testing Suite

# Test configurations - run all prompt tests
testPaths:
  - promptfoo/translate/eval.yaml
  - promptfoo/summary-title/eval.yaml
  - promptfoo/language-detection/eval.yaml
  - promptfoo/emoji-picker/eval.yaml
  - promptfoo/knowledge-qa/eval.yaml
  - promptfoo/abstract-chunk/eval.yaml

# Output configuration
outputPath: promptfoo-results.json

# Default test settings
defaultTest:
  assert:
    - type: llm-rubric
      provider: openai:gpt-5-mini
      value: "The response should be relevant and well-formatted"
    - type: cost
      threshold: 0.01  # Maximum cost per test in USD

# Environment variables for API keys
env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

# Evaluation settings
evaluateOptions:
  maxConcurrency: 5
  delay: 100

# TypeScript support
transforms:
  - "typescript"
